description: 'Example generated boilerplate'
name: 'example'
version: '1.0.0+1'
dependencies: 
  built_collection: '^4.0.0'
  built_value: '^6.1.3'
  cupertino_icons: '^0.1.2'
  flutter_redux: '^0.5.2'
  http: '^0.11.3+16'
  intl: '^0.15.7'
  redux: '^3.0.0'
  redux_epics: '^0.10.0'
  rxdart: '^0.18.1'
  shared_preferences: '0.4.2'
  uri: '0.11.3+1'
  flutter: 
    sdk: 'flutter'
dev_dependencies: 
  build_runner: '^1.0.0'
  built_value_generator: '^6.1.4'
  flutter_launcher_icons: '^0.6.1'
  redux_utils: '^0.0.2'
environment: 
  sdk: '>=2.0.0-dev.68.0 <3.0.0'
flutter: 
  uses-material-design: true
