name: redux_utils
description: A sample command-line application.
version: 0.0.1
# homepage: https://www.example.com
# author: raj <email@example.com>

environment:
  sdk: '>=2.0.0-dev.68.0 <3.0.0'

dependencies:
  path: ^1.4.1
  code_builder: ^3.1.3
  dart_style: ^1.1.3
  built_value: ^6.1.3
  built_collection: ^4.0.0
  args: ^1.5.0
  pubspec: ^0.1.1
  recase: ^2.0.0+1
  tuple: ^1.0.2

dev_dependencies:
  test: ^1.0.0
